id: 'grexx-services'
alias: Grexx MQTT Service Call
description: 'Call any HA service based on MQTT message payload'
trigger:
- platform: mqtt
  topic: home-prefix/service_call
action:
- service: "{{ trigger.payload_json.domain }}.{{ trigger.payload_json.service }}"
  data: "{{ trigger.payload_json.service_data }}"
mode: parallel

