name: "Energyboxx Integration"
description: "Integration for Energyboxx with MQTT bridge and service automation"
version: "1.0.17"
slug: "energyboxx"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  energyboxx_mqtt_host: "ess.grexxconnect.com"
  energyboxx_mqtt_port: 8883
  energyboxx_mqtt_username: ""
  energyboxx_mqtt_password: ""
  mqtt_statestream_base_topic: ""
  mqtt_client_cafile_b64: ""
  mqtt_client_certfile_b64: ""
  mqtt_client_keyfile_b64: ""
  tailscale_authkey: ""
schema:
  energyboxx_mqtt_host: str
  energyboxx_mqtt_port: port
  energyboxx_mqtt_username: str
  energyboxx_mqtt_password: str
  mqtt_statestream_base_topic: str
  mqtt_client_cafile_b64: str
  mqtt_client_certfile_b64: str
  mqtt_client_keyfile_b64: str
  tailscale_authkey: str
logs: true
homeassistant_api: true
hassio_api: true
hassio_role: default
full_access: true
map:
  - config:rw
ports:
  1885/tcp: 1885
services:
  - mqtt:provide
discovery:
  - mqtt
startup: system
watchdog: tcp://[HOST]:1885
privileged:
  - NET_ADMIN
  - NET_RAW
devices:
  - /dev/net/tun
host_network: true
host_dbus: true
